package org.firstinspires.ftc.teamcode.autos; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;

import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;

import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;

/*
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;

import com.pedropathing.ivy.Scheduler;

import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;
*/
@Autonomous
public class auto1 extends OpMode {
    private Follower follower; // creates a follower using our robot configs from Constants.java (ex. drivetrain, localizer, algorithm)
    private final PoseFactory p = PoseFactory.degrees(); // uses degrees, NOT radians (micah)

    // our poses
    // ex. p.of(x, y, heading);
    private final Pose startPose = p.of(24, 24, 0); // where the robot starts the auto / ***EXAMPLE***
    private final Pose park = p.of(48, 48, 90); // where the robot ends / ***EXAMPLE***
    private final Pose controlPose = p.of(36, 60, 45); // ***EXAMPLE***

    /*
    ******** HOW TO MAKE A STRAIGHT PATH ********
    private Path park() {
        return line(startPose, park).linear(startPose, park);
    } */

    /*
    ******** HOW TO MAKE A CURVED PATH ********
    private Path park() {
        return curve(startPose, controlPose, park).linear(startPose, park);
    } */

    @Override
    public void init() { // init runs before start button is pressed
        follower = Constants.create(hardwareMap);
        follower.setPose(startPose); // setPose should now = startPose
    }

    @Override
    public void start() {

    }

    @Override
    public void loop() {

    }
}